@api = http://192.168.1.4:4000/api/auth

###
POST {{api}}/sign-up
Content-Type: application/json

{
    "username": "chicha12",
    "email": "chicha1@gmail.com",
    "password": "123"
}
###
POST {{api}}/sign-in
Content-Type: application/json

{
    "email": "chichadioss23@gmail.com",
    "password": "claudio123"
}