@api = http://192.168.1.4:4000/api/tasks

###
POST {{api}}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJDbGF1ZGlvIiwiaWF0IjoxNjQxNjU1MzU0LCJleHAiOjE2NDE3NDE3NTR9.hJnOIJAg09GFcEGZR1PgqlQyE1GT9mDKzFR5TFX-ekY


{
    "name": "Tengo que limpiar la casa",
    "completed": true,
    "userId": 1
}
###
GET {{api}}
###
GET {{api}}/1
###
DELETE {{api}}/3
###
PUT {{api}}/4
Content-Type: application/json

{
    "name": "Tengo que cocinar xd",
    "completed": false
}